server:
    port: 13142

spring:
    datasource:
        url: jdbc:mysql://47.98.104.98:3306/product?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: jxZ03121994!
    cloud:
        sentinel:
            enabled: true
            transport:
                port: 8719
                dashboard: localhost:13149
#        loadbalancer:
#            nacos:
#                enabled: true
dubbo:
    protocol:
        name: dubbo
        port: 13242

#seata:
#    enabled: true
#    tx-service-group: order-service-group
#    service:
#        vgroup-mapping:
#            order-service-group: default
management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: '*'
