server:
    port: 13142

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rtt_product?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 03121994
#    profiles:
#        active: test
#        include: prod,test
#    cloud:
#        sentinel:
#            enabled: false
#            transport:
#                port: 8719
#                dashboard: localhost:13149
#        loadbalancer:
#            nacos:
#                enabled: true
dubbo:
    protocol:
        name: dubbo
        port: 13152

#seata:
#    enabled: true
#    tx-service-group: order-service-group
#    service:
#        vgroup-mapping:
#            order-service-group: default
management:
    endpoints:
        jmx:
            exposure:
                include: *
        web:
            exposure:
                include: *
