server:
    port: 13148
spring:
    application:
        name: rtt-gateway
    cloud:
        gateway:
            enabled: true
            # 全局跨域配置
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "https://docs.spring.io"
                        allowed-methods:
                            - GET
                            - POST
            routes:
                -   id: rtt-server-route
                    uri: lb://rtt-order
                    predicates:
                        - Path=/order/**,/orderV2/**
                    filters:
                        - StripPrefix=1
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 1000
                response-timeout: 5s
        # 服务发现
        nacos:
            server-addr: http://127.0.0.1:8848
            username: nacos
            password: nacos
            discovery:
                namespace: eshop
                group: dubbo-service
                enabled: true
        # sentinel 控制台
        sentinel:
            enabled: true
            transport:
                dashboard: http://127.0.0.1:13149
                port: 8721
            eager: true
    redis:
        host: 127.0.0.1
        port: 6379
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 8
                max-wait: 200ms
    security:
        user:
            name: rtt
            password: rtt
            roles:
                - "ADMIN"
