server:
    port: 13141
    tomcat:
        threads:
            max: 201
seata:
    enabled: true
    tx-service-group: user-service-group
    registry:
        type: nacos
        nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            group: seata
            namespace: dev
            cluster: default
    config:
        type: nacos
        data-type: properties
        nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            group: seata
            namespace: dev
            data-id: seata-client.properties
    service:
        vgroup-mapping:
            user-service-group: default
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rtt_user?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 03121994
    cloud:
        loadbalancer:
            nacos:
                enabled: true
        sentinel:
            enabled: true
            transport:
                port: 8719
                dashboard: localhost:13149