server:
    port: 13141

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rtt_order?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 03121994
    cloud:
        sentinel:
            enabled: true
            transport:
                dashboard: http://127.0.0.1:13149
                port: 8721
dubbo:
    protocol:
        name: dubbo
        port: 13241

#seata:
#    enabled: true
#    tx-service-group: order-service-group
#    service:
#        vgroup-mapping:
#            order-service-group: default

management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: '*'
