server:
    port: 13142
seata:
    enabled: false
    tx-service-group: order-service-group
    registry:
        type: nacos
        nacos:
            server-addr: http://127.0.0.1:8848
            username: nacos
            password: nacos
            group: seata
            namespace: dev
            cluster: default
    config:
        type: nacos
        data-type: properties
        nacos:
            server-addr: http://127.0.0.1:8848
            username: nacos
            password: nacos
            group: seata
            namespace: dev
            data-id: seata-client.properties
    service:
        vgroup-mapping:
            order-service-group: default
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rtt_order?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 03121994
    cloud:
        sentinel:
            enabled: false
            transport:
                port: 8719
                dashboard: localhost:13149
        loadbalancer:
            nacos:
                enabled: true
    redis:
        host: localhost
        port: 6379
